//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixologyJournalApp.Droid.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixologyJournalApp.Droid.Assets.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Drink.
        /// </summary>
        internal static string AddBarDrink_Text {
            get {
                return ResourceManager.GetString("AddBarDrink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bar Drink.
        /// </summary>
        internal static string AddBarDrinkLabel {
            get {
                return ResourceManager.GetString("AddBarDrinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Recipe.
        /// </summary>
        internal static string AddBaseRecipe_Text {
            get {
                return ResourceManager.GetString("AddBaseRecipe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string AddContextMenu_Label {
            get {
                return ResourceManager.GetString("AddContextMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Homemade Drink.
        /// </summary>
        internal static string AddHomemadeDrinkLabel {
            get {
                return ResourceManager.GetString("AddHomemadeDrinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ingredient.
        /// </summary>
        internal static string AddIngredientMenu_Label {
            get {
                return ResourceManager.GetString("AddIngredientMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homemade Drink.
        /// </summary>
        internal static string AddModifiedRecipe_Text {
            get {
                return ResourceManager.GetString("AddModifiedRecipe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNoteLabel {
            get {
                return ResourceManager.GetString("AddNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Picture.
        /// </summary>
        internal static string AddPictureMenu_Label {
            get {
                return ResourceManager.GetString("AddPictureMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        internal static string AddRecipeLabel {
            get {
                return ResourceManager.GetString("AddRecipeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string AddTextEntry_Text {
            get {
                return ResourceManager.GetString("AddTextEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string BackMenu_Label {
            get {
                return ResourceManager.GetString("BackMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelMenu_Label {
            get {
                return ResourceManager.GetString("CancelMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelOption {
            get {
                return ResourceManager.GetString("CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliter.
        /// </summary>
        internal static string CentiliterUnit {
            get {
                return ResourceManager.GetString("CentiliterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string CentiliterUnitFormat {
            get {
                return ResourceManager.GetString("CentiliterUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliters.
        /// </summary>
        internal static string CentiliterUnitPlural {
            get {
                return ResourceManager.GetString("CentiliterUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string ClearCache_Content {
            get {
                return ResourceManager.GetString("ClearCache.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the cache will remove all locally sourced files which are saved from cloud-based services. Using this button will force this app to download all data once again, but may help in situations where changes to files are not being shown.
        /// </summary>
        internal static string ClearCacheWarning_Text {
            get {
                return ResourceManager.GetString("ClearCacheWarning.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to already be recipes in {0}. Would you like to keep the recipes you were using, or use the recipes in {0}?.
        /// </summary>
        internal static string ConflictDialogDescriptionFormatted {
            get {
                return ResourceManager.GetString("ConflictDialogDescriptionFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        internal static string ConflictDialogHeader {
            get {
                return ResourceManager.GetString("ConflictDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueDialogOption {
            get {
                return ResourceManager.GetString("ContinueDialogOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to connect to the files. You may continue and we will use whatever has been cached locally, or you may retry..
        /// </summary>
        internal static string CouldNotConnectDescription {
            get {
                return ResourceManager.GetString("CouldNotConnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to connect to this service. Please try again later..
        /// </summary>
        internal static string CouldNotConnectDialogDescription {
            get {
                return ResourceManager.GetString("CouldNotConnectDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Drink.
        /// </summary>
        internal static string CreateDrinkMenu_Label {
            get {
                return ResourceManager.GetString("CreateDrinkMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        internal static string CupUnit {
            get {
                return ResourceManager.GetString("CupUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string CupUnitFormat {
            get {
                return ResourceManager.GetString("CupUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        internal static string CupUnitPlural {
            get {
                return ResourceManager.GetString("CupUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash.
        /// </summary>
        internal static string DashUnit {
            get {
                return ResourceManager.GetString("DashUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string DashUnitFormat {
            get {
                return ResourceManager.GetString("DashUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashes.
        /// </summary>
        internal static string DashUnitPlural {
            get {
                return ResourceManager.GetString("DashUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the recipe and any derived recipes. Are you sure you want to do this?.
        /// </summary>
        internal static string DeleteBaseRecipeDialogDescription {
            get {
                return ResourceManager.GetString("DeleteBaseRecipeDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string DeleteDialogHeader {
            get {
                return ResourceManager.GetString("DeleteDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry.
        /// </summary>
        internal static string DeleteEntryMenu_Label {
            get {
                return ResourceManager.GetString("DeleteEntryMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the journal entry, as well as any images connected to it. Are you sure you want to do this?.
        /// </summary>
        internal static string DeleteJournalEntryDialogDescription {
            get {
                return ResourceManager.GetString("DeleteJournalEntryDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Recipe.
        /// </summary>
        internal static string DeleteRecipeMenu_Label {
            get {
                return ResourceManager.GetString("DeleteRecipeMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string DrinksHeader_Header {
            get {
                return ResourceManager.GetString("DrinksHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string DrinksLabel {
            get {
                return ResourceManager.GetString("DrinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        internal static string DropUnit {
            get {
                return ResourceManager.GetString("DropUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string DropUnitFormat {
            get {
                return ResourceManager.GetString("DropUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drops.
        /// </summary>
        internal static string DropUnitPlural {
            get {
                return ResourceManager.GetString("DropUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet!.
        /// </summary>
        internal static string EmptyListText_Text {
            get {
                return ResourceManager.GetString("EmptyListText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string EntryNotes_Header {
            get {
                return ResourceManager.GetString("EntryNotes.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EntryTitle_Header {
            get {
                return ResourceManager.GetString("EntryTitle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogHeader {
            get {
                return ResourceManager.GetString("ErrorDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string FavoriteHeader_Header {
            get {
                return ResourceManager.GetString("FavoriteHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite This Recipe.
        /// </summary>
        internal static string FavoriteMenu_Label {
            get {
                return ResourceManager.GetString("FavoriteMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string IngredientDetails_Header {
            get {
                return ResourceManager.GetString("IngredientDetails.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string IngredientName_Header {
            get {
                return ResourceManager.GetString("IngredientName.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string IngredientQuantity_Header {
            get {
                return ResourceManager.GetString("IngredientQuantity.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string IngredientUnit_Header {
            get {
                return ResourceManager.GetString("IngredientUnit.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string JournalHeader_Header {
            get {
                return ResourceManager.GetString("JournalHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        internal static string KeepOption {
            get {
                return ResourceManager.GetString("KeepOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        internal static string LiterUnit {
            get {
                return ResourceManager.GetString("LiterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string LiterUnitFormat {
            get {
                return ResourceManager.GetString("LiterUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string LiterUnitPlural {
            get {
                return ResourceManager.GetString("LiterUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LocalSourceName {
            get {
                return ResourceManager.GetString("LocalSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationBox_Header {
            get {
                return ResourceManager.GetString("LocationBox.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliter.
        /// </summary>
        internal static string MilliliterUnit {
            get {
                return ResourceManager.GetString("MilliliterUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string MilliliterUnitFormat {
            get {
                return ResourceManager.GetString("MilliliterUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliters.
        /// </summary>
        internal static string MilliliterUnitPlural {
            get {
                return ResourceManager.GetString("MilliliterUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bar Drink.
        /// </summary>
        internal static string NewBarDrink_Header {
            get {
                return ResourceManager.GetString("NewBarDrink.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string NewEntryHeader_Header {
            get {
                return ResourceManager.GetString("NewEntryHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        internal static string NewRecipe_Header {
            get {
                return ResourceManager.GetString("NewRecipe.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextMenu_Label {
            get {
                return ResourceManager.GetString("NextMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Favorite Recipe Chosen Yet!.
        /// </summary>
        internal static string NoFavoriteRecipe_Text {
            get {
                return ResourceManager.GetString("NoFavoriteRecipe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoOption {
            get {
                return ResourceManager.GetString("NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks To Make:.
        /// </summary>
        internal static string NumberOfDrinksCombo_Header {
            get {
                return ResourceManager.GetString("NumberOfDrinksCombo.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Number Of Drinks.
        /// </summary>
        internal static string NumberOfDrinksMenu_Label {
            get {
                return ResourceManager.GetString("NumberOfDrinksMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKOption {
            get {
                return ResourceManager.GetString("OKOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        internal static string OneDriveSourceName {
            get {
                return ResourceManager.GetString("OneDriveSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string OriginalHeader_Header {
            get {
                return ResourceManager.GetString("OriginalHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string OthersHeader_Header {
            get {
                return ResourceManager.GetString("OthersHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        internal static string OunceUnit {
            get {
                return ResourceManager.GetString("OunceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string OunceUnitFormat {
            get {
                return ResourceManager.GetString("OunceUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string OunceUnitPlural {
            get {
                return ResourceManager.GetString("OunceUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixology.
        /// </summary>
        internal static string OverviewTitle_Title {
            get {
                return ResourceManager.GetString("OverviewTitle.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Another File.
        /// </summary>
        internal static string PickAnotherFileOption {
            get {
                return ResourceManager.GetString("PickAnotherFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        internal static string PieceUnit {
            get {
                return ResourceManager.GetString("PieceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string PieceUnitFormat {
            get {
                return ResourceManager.GetString("PieceUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        internal static string PieceUnitPlural {
            get {
                return ResourceManager.GetString("PieceUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinch.
        /// </summary>
        internal static string PinchUnit {
            get {
                return ResourceManager.GetString("PinchUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string PinchUnitFormat {
            get {
                return ResourceManager.GetString("PinchUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinches.
        /// </summary>
        internal static string PinchUnitPlural {
            get {
                return ResourceManager.GetString("PinchUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pint.
        /// </summary>
        internal static string PintUnit {
            get {
                return ResourceManager.GetString("PintUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string PintUnitFormat {
            get {
                return ResourceManager.GetString("PintUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints.
        /// </summary>
        internal static string PintUnitPlural {
            get {
                return ResourceManager.GetString("PintUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string RecipeInstructions_Header {
            get {
                return ResourceManager.GetString("RecipeInstructions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Instructions Here.
        /// </summary>
        internal static string RecipeInstructions_PlaceholderText {
            get {
                return ResourceManager.GetString("RecipeInstructions.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string RecipesHeader_Header {
            get {
                return ResourceManager.GetString("RecipesHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string RecipesLabel {
            get {
                return ResourceManager.GetString("RecipesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string RecipeTitle_Header {
            get {
                return ResourceManager.GetString("RecipeTitle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryDialogOption {
            get {
                return ResourceManager.GetString("RetryDialogOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Notes About The Results Here.
        /// </summary>
        internal static string ReviewNotesBox_PlaceholderText {
            get {
                return ResourceManager.GetString("ReviewNotesBox.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveMenu_Label {
            get {
                return ResourceManager.GetString("SaveMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsHeader_Header {
            get {
                return ResourceManager.GetString("SettingsHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu_Label {
            get {
                return ResourceManager.GetString("SettingsMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Recipes?.
        /// </summary>
        internal static string ShouldSync_Header {
            get {
                return ResourceManager.GetString("ShouldSync.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice.
        /// </summary>
        internal static string SliceUnit {
            get {
                return ResourceManager.GetString("SliceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string SliceUnitFormat {
            get {
                return ResourceManager.GetString("SliceUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slices.
        /// </summary>
        internal static string SliceUnitPlural {
            get {
                return ResourceManager.GetString("SliceUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoon.
        /// </summary>
        internal static string SpoonUnit {
            get {
                return ResourceManager.GetString("SpoonUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string SpoonUnitFormat {
            get {
                return ResourceManager.GetString("SpoonUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoons.
        /// </summary>
        internal static string SpoonUnitPlural {
            get {
                return ResourceManager.GetString("SpoonUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source To Sync From.
        /// </summary>
        internal static string SyncSource_Header {
            get {
                return ResourceManager.GetString("SyncSource.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoon.
        /// </summary>
        internal static string TablespoonUnit {
            get {
                return ResourceManager.GetString("TablespoonUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string TablespoonUnitFormat {
            get {
                return ResourceManager.GetString("TablespoonUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoons.
        /// </summary>
        internal static string TablespoonUnitPlural {
            get {
                return ResourceManager.GetString("TablespoonUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Picture.
        /// </summary>
        internal static string TakePictureMenu_Label {
            get {
                return ResourceManager.GetString("TakePictureMenu.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoon.
        /// </summary>
        internal static string TeaspoonUnit {
            get {
                return ResourceManager.GetString("TeaspoonUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} of {2}.
        /// </summary>
        internal static string TeaspoonUnitFormat {
            get {
                return ResourceManager.GetString("TeaspoonUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoons.
        /// </summary>
        internal static string TeaspoonUnitPlural {
            get {
                return ResourceManager.GetString("TeaspoonUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo is too large to sync remotely. Do you want to pick another file?.
        /// </summary>
        internal static string TooLargeDialogDescription {
            get {
                return ResourceManager.GetString("TooLargeDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Large.
        /// </summary>
        internal static string TooLargeDialogHeader {
            get {
                return ResourceManager.GetString("TooLargeDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Taste.
        /// </summary>
        internal static string ToTasteUnit {
            get {
                return ResourceManager.GetString("ToTasteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {1}.
        /// </summary>
        internal static string ToTasteUnitFormat {
            get {
                return ResourceManager.GetString("ToTasteUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Taste.
        /// </summary>
        internal static string ToTasteUnitPlural {
            get {
                return ResourceManager.GetString("ToTasteUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twist.
        /// </summary>
        internal static string TwistUnit {
            get {
                return ResourceManager.GetString("TwistUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {2} {1}.
        /// </summary>
        internal static string TwistUnitFormat {
            get {
                return ResourceManager.GetString("TwistUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twists.
        /// </summary>
        internal static string TwistUnitPlural {
            get {
                return ResourceManager.GetString("TwistUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownUnit {
            get {
                return ResourceManager.GetString("UnknownUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}.
        /// </summary>
        internal static string UnknownUnitFormat {
            get {
                return ResourceManager.GetString("UnknownUnitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownUnitPlural {
            get {
                return ResourceManager.GetString("UnknownUnitPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}.
        /// </summary>
        internal static string UseOptionFormatted {
            get {
                return ResourceManager.GetString("UseOptionFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesOption {
            get {
                return ResourceManager.GetString("YesOption", resourceCulture);
            }
        }
    }
}
