INSERT INTO Ingredients(RecipeId, Name, Brand, AmountUnit, AmountQuantity) VALUES
    (1, 'White Peach Puree', '', 'Ounce', '2'),
    (1, 'Prosecco ', '', 'Ounce', '3.5'),
    (2, 'Pitú Cachaça', '', 'Ounce', '1.5'),
    (2, 'Triple Sec', '', 'Ounce', '1.5'),
    (2, 'Lime Juice', '', 'Ounce', '0.5'),
    (3, 'Lime Wedge', '', 'Piece', '6'),
    (3, 'Sugar', '', 'Tablespoon', '1'),
    (3, 'Cachaça', '', 'Ounce', '3'),
    (4, 'Light Rum', '', 'Ounce', '2'),
    (4, 'Lime Juice', '', 'Ounce', '1'),
    (4, 'Cola', '', 'Ounce', '3'),
    (4, 'Lime Wedge', '', 'Piece', '1'),
    (5, 'Light Rum', '', 'Ounce', '2'),
    (5, 'Lime Juice', '', 'Ounce', '1'),
    (5, 'Simple Syrup', '', 'Ounce', '0.5'),
    (5, 'Lime Wedge', '', 'Piece', '1'),
    (6, 'Bermudan Rum', '', 'Ounce', '2'),
    (6, 'Ginger Beer', '', 'Ounce', '3'),
    (6, 'Lime Wedge', '', 'Piece', '1'),
    (7, 'Light Rum', '', 'Ounce', '1.5'),
    (7, 'Sweet Vermouth', '', 'Ounce', '0.5'),
    (7, 'Lime Juice', '', 'Ounce', '0.5'),
    (7, 'White Crème de cacao', '', 'Dash', '1'),
    (7, 'Grenadine', '', 'Dash', '1'),
    (8, 'Gin', '', 'Ounce', '2'),
    (8, 'Triple Sec', '', 'Ounce', '0.5'),
    (8, 'Pineapple Juice', '', 'Ounce', '0.5'),
    (8, 'Angostura', '', 'Dash', '2'),
    (9, 'Light Rum', '', 'Ounce', '1.5'),
    (9, 'Dark Rum', '', 'Ounce', '1.5'),
    (9, 'Orange Juice', '', 'Ounce', '1'),
    (9, 'Lemon Juice', '', 'Ounce', '1'),
    (9, 'Passionfruit Juice', '', 'Ounce', '2'),
    (9, 'Simple Syrup', '', 'Ounce', '0.5'),
    (9, 'Grenadine', '', 'Dash', '1'),
    (9, 'Maraschino Cherry', '', 'Piece', '1'),
    (9, 'Orange wheel', '', 'Piece', '1'),
    (10, 'Vodka', '', 'Ounce', '1.5'),
    (10, 'Triple Sec', '', 'Ounce', '1'),
    (10, 'Lime Juice', '', 'Ounce', '0.5'),
    (11, 'Jamaican Rum', '', 'Ounce', '1'),
    (11, 'Light Rum', '', 'Ounce', '1'),
    (11, 'Triple Sec', '', 'Ounce', '0.5'),
    (11, 'Orgeat Syrup', '', 'Ounce', '0.75'),
    (11, 'Lime Juice', '', 'Ounce', '1'),
    (11, 'Mint Sprig', '', 'Piece', '1'),
    (12, 'White Tequila', '', 'Ounce', '1.5'),
    (12, 'Triple Sec', '', 'Ounce', '1'),
    (12, 'Lime Juice', '', 'Ounce', '0.5'),
    (13, 'Lime', '', 'Slice', '4'),
    (13, 'Sugar', '', 'Teaspoon', '3'),
    (13, 'Mint Leaves', '', 'Piece', '10'),
    (13, 'Light Rum', '', 'Ounce', '2'),
    (13, 'Club Soda', '', 'Ounce', '4'),
    (13, 'Mint Sprigs', '', 'Piece', '2'),
    (14, 'Dark Rum', '', 'Ounce', '2'),
    (14, 'Pineapple Juice', '', 'Ounce', '2'),
    (14, 'Coconut Cream', '', 'Ounce', '1.5'),
    (14, 'Maraschino Cherry', '', 'Piece', '1'),
    (14, 'Pineapple Cube', '', 'Piece', '1'),
    (15, 'Vodka', '', 'Ounce', '2'),
    (15, 'Orange Juice', '', 'Ounce', '3'),
    (16, 'Vodka', '', 'Ounce', '2'),
    (16, 'Cranberry Juice', '', 'Ounce', '1.5'),
    (16, 'Grapefruit Juice', '', 'Ounce', '1.5'),
    (16, 'Lime Wedge', '', 'Piece', '1'),
    (17, 'Vodka', '', 'Ounce', '1.5'),
    (17, 'Peach Schnapps', '', 'Ounce', '0.5'),
    (17, 'Cranberry Juice', '', 'Ounce', '1.5'),
    (17, 'Orange Juice', '', 'Ounce', '1.5'),
    (18, 'Tequila', '', 'Ounce', '2.5'),
    (18, 'Orange Juice ', '', 'Ounce', '3'),
    (18, 'Grenadine', '', 'Dash', '2'),
    (19, 'Dark Rum', '', 'Ounce', '1'),
    (19, 'Añejo Rum', '', 'Ounce', '1.5'),
    (19, 'Light Rum', '', 'Ounce', '1.5'),
    (19, 'Applejack', '', 'Ounce', '0.75'),
    (19, 'Papaya Nectar', '', 'Ounce', '0.75'),
    (19, 'Pineapple Juice', '', 'Ounce', '0.75'),
    (19, 'Lime Juice', '', 'Ounce', '1'),
    (19, 'Simple Syrup', '', 'Ounce', '0.5'),
    (19, '151-proof Rum', '', 'Ounce', '0.5'),
    (19, 'Maraschino Cherry', '', 'Piece', '1'),
    (19, 'Pineapple Spear', '', 'Piece', '1'),
    (19, 'Mint Sprig', '', 'Piece', '1'),
    (20, 'Dry Gin', '', 'Ounce', '2'),
    (20, 'White Crème de Cacao', '', 'Ounce', '1'),
    (20, 'Cream', '', 'Ounce', '1'),
    (21, 'Vodka', '', 'Ounce', '1.5'),
    (21, 'Tomato Juice', '', 'Cup', '0.75'),
    (21, 'Worcestershire Sauce', '', 'Dash', '2'),
    (21, 'Tabasco Sauce', '', 'Dash', '1'),
    (21, 'Horseradish', '', 'Teaspoon', '0.75'),
    (21, 'Salt', '', 'Pinch', '1'),
    (21, 'Black Pepper', '', 'Dash', '1'),
    (21, 'Lemon Juice', '', 'Teaspoon', '0.25'),
    (21, 'Celery Stalk', '', 'Piece', '1'),
    (21, 'Lemon Wedge', '', 'Piece', '1'),
    (22, 'Citrus Vodka', '', 'Ounce', '1.5'),
    (22, 'Triple Sec', '', 'Ounce', '1'),
    (22, 'Lime Juice', '', 'Ounce', '0.5'),
    (22, 'Cranberry Juice', '', 'Dash', '2'),
    (22, 'Lime Wedge', '', 'Piece', '1'),
    (23, 'Simple Syrup', '', 'Teaspoon', '0.5'),
    (23, 'Lemon Juice ', '', 'Ounce', '0.5'),
    (23, 'Gin', '', 'Ounce', '1'),
    (23, 'Champagne', '', 'Ounce', '4'),
    (24, 'Gin', '', 'Ounce', '2'),
    (24, 'Tonic', '', 'Ounce', '3'),
    (24, 'Lime Wedge', '', 'Piece', '1'),
    (25, 'Green Crème de Menthe', '', 'Ounce', '1.5'),
    (25, 'White Crème de Cacao', '', 'Ounce', '1.5'),
    (25, 'Cream', '', 'Ounce', '1'),
    (26, 'Vodka', '', 'Ounce', '1'),
    (26, 'Gin', '', 'Ounce', '1'),
    (26, 'Light Rum', '', 'Ounce', '1'),
    (26, 'White Tequila', '', 'Ounce', '1'),
    (26, 'Triple Sec', '', 'Ounce', '1'),
    (26, 'Lemon Juice', '', 'Ounce', '1'),
    (26, 'Simple Syrup', '', 'Ounce', '0.75'),
    (26, 'Cola', '', 'Ounce', '3'),
    (26, 'Lemon Wedge', '', 'Piece', '1'),
    (27, 'Bourbon ', '', 'Ounce', '2'),
    (27, 'Sweet Vermouth', '', 'Ounce', '1'),
    (27, 'Angostura Bitters', '', 'Dash', '2'),
    (27, 'Maraschino Cherry ', '', 'Piece', '1'),
    (28, 'Gin', '', 'Ounce', '2.5'),
    (28, 'Dry Vermouth', '', 'Ounce', '0.5'),
    (28, 'Orange', '', 'Twist', '1'),
    (29, 'Triple Sec', '', 'Ounce', '0.5'),
    (29, 'Orange Juice ', '', 'Ounce', '1.5'),
    (29, 'Champagne ', '', 'Ounce', '3.5'),
    (29, 'Orange', '', 'Slice', '1'),
    (30, 'Bourbon ', '', 'Ounce', '3'),
    (30, 'Simple Syrup', '', 'Ounce', '2'),
    (30, 'Mint Sprig', '', 'Piece', '5'),
    (31, 'Vodka', '', 'Ounce', '2'),
    (31, 'Ginger Beer', '', 'Ounce', '3'),
    (31, 'Lime Wedge', '', 'Piece', '2'),
    (32, 'Campari ', '', 'Ounce', '1.5'),
    (32, 'Sweet Vermouth ', '', 'Ounce', '1.5'),
    (32, 'Gin', '', 'Ounce', '1.5'),
    (32, 'Orange', '', 'Twist', '1'),
    (33, 'Pimm''s No. 1 Cup', '', 'Ounce', '2'),
    (33, 'Ginger Ale', '', 'Ounce', '7'),
    (33, 'Cucumber', '', 'Slice', '1'),
    (34, 'Pisco Brandy', '', 'Ounce', '2'),
    (34, 'Lemon Juice', '', 'Ounce', '1'),
    (34, 'Simple Syrup', '', 'Ounce', '0.5'),
    (34, 'Egg White', '', 'Piece', '1'),
    (34, 'Angostura Bitters', '', 'Dash', '2'),
    (35, 'Scotch', '', 'Ounce', '2.5'),
    (35, 'Drambuie', '', 'Ounce', '0.5'),
    (36, 'Rye Whiskey', '', 'Ounce', '3'),
    (36, 'Simple Syrup', '', 'Ounce', '0.75'),
    (36, 'Peychaud''s Bitters', '', 'Dash', '4'),
    (36, 'Lemon', '', 'Twist', '1'),
    (37, 'Cognac', '', 'Ounce', '1.5'),
    (37, 'Triple Sec', '', 'Ounce', '1'),
    (37, 'Lemon Juice', '', 'Ounce', '0.5'),
    (37, 'Lemon', '', 'Twist', '1'),
    (38, 'Gin', '', 'Ounce', '2.5'),
    (38, 'Lemon Juice', '', 'Ounce', '1'),
    (38, 'Simple Syrup', '', 'Ounce', '0.75'),
    (38, 'Club Soda', '', 'Ounce', '3'),
    (38, 'Maraschino Cherry', '', 'Piece', '1'),
    (38, 'Half Orange Wheel', '', 'Piece', '1'),
    (39, 'Whiskey', '', 'Ounce', '2'),
    (39, 'Simple Syrup', '', 'Ounce', '0.5'),
    (40, 'Whiskey', '', 'Ounce', '2'),
    (40, 'Lemon Juice ', '', 'Ounce', '1'),
    (40, 'Simple Syrup', '', 'Ounce', '0.5'),
    (40, 'Maraschino Cherry', '', 'Piece', '1'),
    (40, 'Half Wheel Orange', '', 'Piece', '1')