INSERT INTO RECIPES (Title, Instructions, UserId) VALUES  
  ('Bellini', 'Add prosecco to puree slowly while mixing.', 1),
  ('Cacharita', 'Shake and strain into cocktail glass.', 1),
  ('Caipirinha', 'Muddle limes and sugar in an old-fashioned glass.||Add crushed ice and cachaça and stir.', 1),
  ('Cuba Libre', 'Build in order in a highball glass.||Garnish with lime wedge.', 1),
  ('Daiquiri', 'Shake and strain into ice-filled wine glass.||Garnish with lime wedge.', 1),
  ('Dark & Stormy', 'Build in an ice-filled highball glass||Garnish with a lime wedge.', 1),
  ('El Floridita', 'Shake and strain into cocktail glass.', 1),
  ('Hawaiian Cocktail', 'Shake and strain into cocktail glass.', 1),
  ('Hurricane', 'Shake and strain into ice-filled hurricane glass.||Garnish with orange and cherry.', 1),
  ('Kamikaze', 'Shake and strain into cocktail glass.', 1),
  ('Mai Tai', 'Shake and strain into crushed ice filled old-fashioned glass.||Garnish with mint.', 1),
  ('Margarita', 'Shake and strain into salt-rimmed cocktail glass.', 1),
  ('Mojito', 'Muddle lime wedges, sugar and mint leaves in mixing glass.||Add ice and rum to the mixing glass.||Shake.||Strain into Collins glass filled with crushed ice.||Top with club soda, and garnish with mint sprigs.', 1),
  ('Piña Colada', 'Shake and strain rum, pineapple juice and coconut cream into Collins glass.||Garnish with cherry and pineapple.', 1),
  ('Screwdriver', 'Build in a highball glass.', 1),
  ('Sea Breeze', 'Build in an ice-filled highball glass, using the lime wedge as garnish.', 1),
  ('Sex on the Beach', 'Build in an ice-filled highball glass.', 1),
  ('Tequila Sunrise', 'Build in an ice-filled Collins glass, dripping the Grenadine in the middle at the end.', 1),
  ('Zombie', 'Shake the first eight ingredients together.||Strain into an ice-filled zombie glass.||Float the 151-proof rum.||Add garnishes.', 1),
  ('Alexander', 'Shake and strain into cocktail glass.', 1),
  ('Bloody Mary', 'Shake and strain into ice-filled Collins glass.||Add celery and lemon as garnish.', 1),
  ('Cosmopolitan', 'Shake and strain into cocktail glass.||Add the garnish.', 1),
  ('French 75', 'Build in a Collins glass filled with crushed ice.||Stir briefly.', 1),
  ('Gin & Tonic', 'Build in an ice-filled Collins glass.||Add the garnish.', 1),
  ('Grasshopper', 'Shake and strain into cocktail glass.', 1),
  ('Long Island Iced Tea', 'Shake everything except the cola.||Strain into ice-filled Collins glass.||Top with cola.||Add the garnish.', 1),
  ('Manhattan', 'Shake and strain into cocktail glass.||Add the garnish.', 1),
  ('Martini', 'Shake and strain into cocktail glass.||Make the orange twist in the presence of the glass.||Express the twist across the rim and drop in.', 1),
  ('Mimosa', 'Build in a Champagne flute.||Add the garnish.', 1),
  ('Mint Julep ', 'Fill julep cup two-thirds full with crushed ice.||Add bourbon and syrup.||Stir.||Add more crushed ice.||Stir.||Add more crushed ice.||Garnish with mint.', 1),
  ('Moscow Mule', 'Build in an ice-filled highball glass.||Add the garnish', 1),
  ('Negroni', 'Build in an ice-filled rocks glass.||Add the garnish.', 1),
  ('Pimm''s Cup', 'Build in a pint glass.||Add the garnish.', 1),
  ('Pisco Sour', 'Shake all but the bitters.||Strain into a Champagne flute.||Add the bitters.', 1),
  ('Rusty Nail', 'Shake and strain into an old-fashioned glass.', 1),
  ('Sazerac', 'Rinse Champagne flute with herbsaint.||Stir other ingredients together.||Strain into flute.||Add the garnish.', 1),
  ('Sidecar', 'Rim cocktail glass with sugar.||Shake other ingredients together.||Strain into cocktail glass.||Add the garnish.', 1),
  ('Tom Collins', 'Shake everything except club soda.||Strain into ice-filled Collins glass.||Top with club soda.||Add the garnishes.', 1),
  ('Old Fashioned', 'Build in ice-filled rocks glass.||Stir.', 1),
  ('Whiskey Sour', 'Shake together.||Strain into ice-filled rocks glass.||Add the garnish.', 1)