CREATE TABLE [dbo].[Users]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	GoogleId VARCHAR(100) NULL,
	MicrosoftId VARCHAR(100) NULL,
	AppleId VARCHAR(100) NULL, 
    [IsDefault] BIT NOT NULL DEFAULT 0
)
